### ISSUE TITLE
Get owners from JFrog logs

### ISSUE THREAD

**Issue by midav7** [jfrog/log-analytics-splunk#12]
I want to create a simple Splunk dashboard with all JFrog artifacts and corresponding owner/creator of artifact. The question is whether I can retrieve owners of artifacts(names) from JFrog logs? I'm just curious if I'm looking in a right direction. I appreciate any advice. Thanks in advance!

**Comment by peters95** [comment]
hi @midav7 this project is comprised of three parts:

1. Installation of Fluentd
2. Configuration of Fluentd to ship data to Splunk HEC thru a valid token and/or SSL.
3. Splunkbase app with existing dashboards

The dashboard capabilities can be seen on Splunkbase here:

https://splunkbase.splunk.com/app/5023/

You can definitely pick and choose what you want to use. You can edit the dashboard and add additional widgets you desire or make a completely new dashboard..

Fluentd will render the data for you into a JSON format which makes life easier in Splunk as the fields are already extracted.

Let me know if you have any further questions. Thanks!

**Comment by peters95** [comment]
hi @midav7 to answer your question on the available fields in the logs please see the wiki:

https://www.jfrog.com/confluence/display/JFROG/Logging

This will contain each field from each relevant log file that you could use.

I see a Username field in Request Log this may be the field you are looking for but it's difficult to discern based upon your description.

**Comment by midav7** [comment]
Thank you! This may be what I'm looking for. I need to find a log sample(http request) where User creates new Artifact, if such activity is logged, then it will work for me.

**Comment by peters95** [comment]
Let me know if we can help with anything else or I will close this issue due to inactivity in a few days. Thanks!
