### ISSUE TITLE
Unable to view logs in Splunk 

### ISSUE THREAD

**Issue by SaiAvinash1205** [jfrog/log-analytics-splunk#59]
Hi Mahitha, I can see only the HTTP events in the splunk. No other logs are getting ingested into the splunk.

**Comment by SaiAvinash1205** [comment]
I see only sourcetype =http

![image](https://github.com/jfrog/log-analytics-splunk/assets/119487065/532dd9c4-6f4c-4f1e-8cf8-c5bfef8d6a29)

**Comment by benharosh** [comment]
This ticket is missing context of used configuration. Since the ticket is old closing it. Please feel free to open with more context if facing the same issue again.
