### ISSUE TITLE
fluentd unable to find concat plugin

### ISSUE THREAD

**Issue by audiolomb** [jfrog/log-analytics-splunk#66]
All 4 required plugins are installed, including concat:

```
fluent-gem install fluent-plugin-concat
Fetching fluent-plugin-concat-2.5.0.gem
Successfully installed fluent-plugin-concat-2.5.0
Parsing documentation for fluent-plugin-concat-2.5.0
Installing ri documentation for fluent-plugin-concat-2.5.0
Done installing documentation for fluent-plugin-concat after 0 seconds
1 gem installed
```
However, when starting fluentd, I am getting this error:

`[error]: config error file="/etc/calyptia-fluentd/calyptia-fluentd.conf" error_class=Fluent::NotFoundPluginError error="Unknown filter plugin 'concat'. Run 'gem search -rd fluent-plugin' to find plugins"`

I am stuck on this and can't seem to find a way to move forward.

**Comment by benharosh** [comment]
I understood that support via support channels was given to this issue.
For future reference,  the error is indicating that fluentd process when started can't find the `concat` gem. To tackle similar issues please run the fluentd start command from the same folder that contains the ruby gems (`concat` in this example) and the error will disappear (or find a way to have the gems available to the fluentd process if running from a different folder .
